# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift
env:
  global:
    - WORKSPACE=Hyperspace.xcworkspace
    - IOS_FRAMEWORK_SCHEME=Hyperspace_iOS
    - TVOS_FRAMEWORK_SCHEME=Hyperspace_tvOS
    - WATCHOS_FRAMEWORK_SCHEME=Hyperspace_watchOS
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=11.2,name=iPhone X"                        SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="YES" POD_LINT="YES"

    - DESTINATION="platform=tvOS Simulator,OS=11.2,name=Apple TV 4K"                    SCHEME="$TVOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES" POD_LINT="NO"

    - DESTINATION="platform=watchOS Simulator,OS=4.2,name=Apple Watch Series 3 - 42mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME"  RUN_TESTS="NO"  POD_LINT="NO"
cache:
  directories:
    - Carthage
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS,tvOS,watchOS --cache-builds
  - npm install -g danger
script:
  - swiftlint
  - set -o pipefail

  # Build Framework and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES | xcpretty;
    else
      xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
  
  # Run Danger
  - danger process danger-swift
after_success:
  - bash <(curl -s https://codecov.io/bash)
